// request
export const SUCCESS_GET_CUSTOMER_ANALYTICS = 'SUCCESS_GET_CUSTOMER_ANALYTICS';
export const FAILURE_GET_CUSTOMER_ANALYTICS = 'FAILURE_GET_CUSTOMER_ANALYTICS';

// filter
export const INPUT_FILTER_CUSTOMER_CODE = 'INPUT_FILTER_CUSTOMER_CODE';
export const INPUT_FILTER_START_DATE = 'INPUT_FILTER_START_DATE';
export const INPUT_FILTER_END_DATE = 'INPUT_FILTER_END_DATE';

// reset
export const RESET_SEARCH_FIELDS = 'RESET_SEARCH_FIELDS';
