// request Get
export const SUCCESS_GET_ALL_INVOICES = 'SUCCESS_GET_ALL_INVOICES';
export const FAILURE_GET_ALL_INVOICES = 'FAILURE_GET_ALL_INVOICES';

// select
export const SELECT_ONE_INVOICE = 'SELECT_ONE_INVOICE';
