// request
export const SUCCESS_GET_PAYMENT_JOURNALS = 'SUCCESS_GET_PAYMENT_JOURNALS';
export const FAILURE_GET_PAYMENT_JOURNALS = 'FAILURE_GET_PAYMENT_JOURNALS';

export const GET_NUMBER_OF_PAYMENT_JOURNAL = 'GET_NUMBER_OF_PAYMENT_JOURNAL';
