// request
export const SUCCESS_GET_PAYMENT_JOURNALS = 'SUCCESS_GET_PAYMENT_JOURNALS';
export const FAILURE_GET_PAYMENT_JOURNALS = 'FAILURE_GET_PAYMENT_JOURNALS';

// select
export const SELECT_ONE_PAYMENT_JOURNAL = 'SELECT_ONE_PAYMENT_JOURNAL';
