// request
export const SUCCESS_CREATE_SALES_INVOICE = 'SUCCESS_CREATE_SALES_INVOICE';
export const FAILURE_CREATE_SALES_INVOICE = 'FAILURE_CREATE_SALES_INVOICE';

// input
export const INPUT_SALES_INVOICE_CUSTOMER = 'INPUT_SALES_INVOICE_CUSTOMER';
export const INPUT_SALES_INVOICE_NUMBER = 'INPUT_SALES_INVOICE_NUMBER';
export const INPUT_SALES_INVOICE_DATE = 'INPUT_SALES_INVOICE_DATE';
export const INPUT_SALES_INVOICE_DUE = 'INPUT_SALES_INVOICE_DUE';
export const INPUT_SALES_INVOICE_TOTAL = 'INPUT_SALES_INVOICE_TOTAL';
