// request Create
export const SUCCESS_CREATE_CUSTOMER = 'SUCCESS_CREATE_CUSTOMER';
export const FAILURE_CREATE_CUSTOMER = 'FAILURE_CREATE_CUSTOMER';
// input
export const INPUT_CUSTOMER_NAME = 'INPUT_CUSTOMER_NAME';
export const INPUT_CUSTOMER_ADDRESS = 'INPUT_CUSTOMER_ADDRESS';
export const INPUT_CUSTOMER_TAX_NUMBER = 'INPUT_CUSTOMER_TAX_NUMBER';
export const INPUT_CUSTOMER_BANK_ACCOUNT = 'INPUT_CUSTOMER_BANK_ACCOUNT';
export const INPUT_CUSTOMER_CITY = 'INPUT_CUSTOMER_CITY';
export const INPUT_CUSTOMER_STATE = 'INPUT_CUSTOMER_STATE';
export const INPUT_CUSTOMER_ZIP_CODE = 'INPUT_CUSTOMER_ZIP_CODE';
export const INPUT_CUSTOMER_TYPE = 'INPUT_CUSTOMER_TYPE';
export const INPUT_CUSTOMER_TELEPHONE = 'INPUT_CUSTOMER_TELEPHONE';
export const INPUT_CUSTOMER_EMAIL = 'INPUT_CUSTOMER_EMAIL';
export const INPUT_CUSTOMER_LANGUAGE = 'INPUT_CUSTOMER_LANGUAGE';
export const INPUT_CUSTOMER_CURRENCY = 'INPUT_CUSTOMER_CURRENCY';
