// request
export const SUCCESS_GET_ALL_CUSTOMERS = 'SUCCESS_GET_ALL_CUSTOMERS';
export const FAILURE_GET_ALL_CUSTOMERS = 'FAILURE_GET_ALL_CUSTOMERS';

// request get one
export const SUCCESS_GET_ONE_CUSTOMER = 'SUCCESS_GET_ONE_CUSTOMER';
export const FAILURE_GET_ONE_CUSTOMER = 'FAILURE_GET_ONE_CUSTOMER';

// select
export const SELECT_ONE_CUSTOMER = 'SELECT_ONE_CUSTOMER';
