// request Create
export const SUCCESS_CREATE_VENDOR = 'SUCCESS_CREATE_VENDOR';
export const FAILURE_CREATE_VENDOR = 'FAILURE_CREATE_VENDOR';
// input
export const INPUT_VENDOR_NAME = 'INPUT_VENDOR_NAME';
export const INPUT_VENDOR_ADDRESS = 'INPUT_VENDOR_ADDRESS';
export const INPUT_VENDOR_TAX_NUMBER = 'INPUT_VENDOR_TAX_NUMBER';
export const INPUT_VENDOR_BANK_ACCOUNT = 'INPUT_VENDOR_BANK_ACCOUNT';
export const INPUT_VENDOR_CITY = 'INPUT_VENDOR_CITY';
export const INPUT_VENDOR_ZIP_CODE = 'INPUT_VENDOR_ZIP_CODE';
export const INPUT_VENDOR_TELEPHONE = 'INPUT_VENDOR_TELEPHONE';
export const INPUT_VENDOR_EMAIL = 'INPUT_VENDOR_EMAIL';
export const INPUT_VENDOR_LANGUAGE = 'INPUT_VENDOR_LANGUAGE';
export const INPUT_VENDOR_CURRENCY = 'INPUT_VENDOR_CURRENCY';
