// request Create
export const SUCCESS_CREATE_VENDOR = 'SUCCESS_CREATE_VENDOR';
export const FAILURE_CREATE_VENDOR = 'FAILURE_CREATE_VENDOR';
// input
export const INPUT_VENDOR_NAME = 'INPUT_VENDOR_NAME';
export const INPUT_VENDOR_ADDRESS = 'INPUT_VENDOR_ADDRESS';
