export const DATABASE_CONNECTION = 'DATABASE_CONNECTION';
export const ACCOUNTS_REPOSITORY = 'ACCOUNTS_REPOSITORY';
export const TRANSACTIONS_REPOSITORY = 'TRANSACTIONS_REPOSITORY';
export const VENDOR_REPOSITORY = 'VENDOR_REPOSITORY';
export const INVOICE_REPOSITORY = 'INVOICE_REPOSITORY';
export const CUSTOMER_REPOSITORY = 'CUSTOMER_REPOSITORY';
export const SALES_INVOICE_REPOSITORY = 'SALES_INVOICE_REPOSITORY';
