// request Create
export const SUCCESS_CREATE_INVOICE = 'SUCCESS_CREATE_INVOICE';
export const FAILURE_CREATE_INVOICE = 'FAILURE_CREATE_INVOICE';

// input
export const INPUT_INVOICE_VENDOR = 'INPUT_INVOICE_VENDOR';
export const INPUT_INVOICE_NUMBER = 'INPUT_INVOICE_NUMBER';
export const INPUT_INVOICE_DATE = 'INPUT_INVOICE_DATE';
export const INPUT_INVOICE_DUE = 'INPUT_INVOICE_DUE';
export const INPUT_INVOICE_TOTAL = 'INPUT_INVOICE_TOTAL';
