// request
export const SUCCESS_CREATE_PAYMENT_TRANSACTION =
  'SUCCESS_CREATE_PAYMENT_TRANSACTION';
export const FAILURE_CREATE_PAYMENT_TRANSACTION =
  'FAILURE_CREATE_PAYMENT_TRANSACTION';

// input
export const INPUT_CREATE_PAYMENT_VENDOR = 'INPUT_CREATE_PAYMENT_VENDOR';
export const INPUT_CREATE_PAYMENT_CUSTOMER = 'INPUT_CREATE_PAYMENT_CUSTOMER';
export const INPUT_CREATE_PAYMENT_ACCOUNT = 'INPUT_CREATE_PAYMENT_ACCOUNT';
export const INPUT_CREATE_PAYMENT_INVOICE = 'INPUT_CREATE_PAYMENT_INVOICE';
export const INPUT_CREATE_PAYMENT_DESCRIPTION =
  'INPUT_CREATE_PAYMENT_DESCRIPTION';
export const INPUT_CREATE_PAYMENT_DATE = 'INPUT_CREATE_PAYMENT_DATE';
export const INPUT_CREATE_PAYMENT_DEBIT = 'INPUT_CREATE_PAYMENT_DEBIT';
export const INPUT_CREATE_PAYMENT_CREDIT = 'INPUT_CREATE_PAYMENT_CREDIT';

// select
export const SELECT_NEW_ROW = 'SELECT_NEW_ROW';

// total
export const TRANSACTION_TOTAL = 'TRANSACTION_TOTAL';
