// request
export const SUCCESS_GET_ALL_SALES_INVOICES = 'SUCCESS_GET_ALL_SALES_INVOICES';
export const FAILURE_GET_ALL_SALES_INVOICES = 'FAILURE_GET_ALL_SALES_INVOICES';

// select
export const SELECT_ONE_SALES_INVOICE = 'SELECT_ONE_SALES_INVOICE';
