// request New
export const SUCCESS_CREATE_TRANSACTIONS = 'SUCCESS_CREATE_TRANSACTIONS';
export const FAILURE_CREATE_TRANSACTIONS = 'FAILURE_CREATE_TRANSACTIONS';

// input
export const INPUT_TRANSACTIONS_ACCOUNT = 'INPUT_TRANSACTIONS_ACCOUNT';
export const INPUT_TRANSACTIONS_VENDOR = 'INPUT_TRANSACTIONS_VENDOR';
export const INPUT_TRANSACTIONS_INVOICE = 'INPUT_TRANSACTIONS_INVOICE';
export const INPUT_TRANSACTIONS_DESCRIPTION = 'INPUT_TRANSACTIONS_DESCRIPTION';
export const INPUT_TRANSACTIONS_DATE = 'INPUT_TRANSACTIONS_DATE';
export const INPUT_TRANSACTIONS_DEBIT = 'INPUT_TRANSACTIONS_DEBIT';
export const INPUT_TRANSACTIONS_CREDIT = 'INPUT_TRANSACTIONS_CREDIT';

// select
export const SELECT_NEW_ROW = 'SELECT_NEW_ROW';

// total
export const TRANSACTION_TOTAL = 'TRANSACTION_TOTAL';
