// request
export const SUCCESS_CREATE_PAYMENT_JOURNAL = 'SUCCESS_CREATE_PAYMENT_JOURNAL';
export const FAILURE_CREATE_PAYMENT_JOURNAL = 'FAILURE_CREATE_PAYMENT_JOURNAL';

// input
export const INPUT_PAYMENT_JOURNAL_DESCRIPTION =
  'INPUT_PAYMENT_JOURNAL_DESCRIPTION';
export const INPUT_PAYMENT_JOURNAL_DATE = 'INPUT_PAYMENT_JOURNAL_DATE';
export const INPUT_PAYMENT_JOURNAL_USER = 'INPUT_PAYMENT_JOURNAL_USER';
