// request
export const SUCCESS_GET_DETAIL_ACCOUNT_REPORT =
  'SUCCESS_GET_DETAIL_ACCOUNT_REPORT';
export const FAILURE_GET_DETAIL_ACCOUNT_REPORT =
  'FAILURE_GET_DETAIL_ACCOUNT_REPORT';

// filter input
export const INPUT_FILTER_ACCOUNT_CODE = 'INPUT_FILTER_ACCOUNT_CODE';
export const INPUT_FILTER_START_DATE = 'INPUT_FILTER_START_DATE';
export const INPUT_FILTER_END_DATE = 'INPUT_FILTER_END_DATE';

// reset
export const RESET_SEARCH_FIELDS = 'RESET_SEARCH_FIELDS';
